main: me.lowlauch.multipleworlds.Main
name: MultipleWorlds
version: '1.2'
description: Allows you to use multiple worlds on a freebuild server
author: lowlauch
api-version: 1.16
depend:
  # These plugins are required for creating multiple worlds and linking the right nether with the right world.
  - Multiverse-Core
  - Multiverse-NetherPortals
softdepend:
  - ProtocolSupport # This plugin allows players on older versions to connect and getting the player's client version
commands:
  mworld:
    description: Command for creating worlds and all kinds of stuff
    usage: /mworld <parameters>
  switch:
    description: Switches worlds
    usage: /switch <world>